### ISSUE TITLE
Error armhf nexus 5, 

### ISSUE THREAD

**Issue by wolfyy59** [Shubhamvis98/toolchains#2]
I followed the clang video that what it gave 
![PXL_20240623_145634504](https://github.com/Shubhamvis98/toolchains/assets/60975463/e0eee4a8-9729-4efc-973e-0476d1949d4c)
![PXL_20240623_145704190 MP](https://github.com/Shubhamvis98/toolchains/assets/60975463/08bde482-64d5-4005-8e95-778fd148144d)

i used this kernel 
and your toolchain 
try to compile one for me with vhci internal bluetooth module 
i'll donate :D

**Comment by Shubhamvis98** [comment]
closing as its a duplicate issue. #3
